security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
   
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
   
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
       
        api:
            pattern: ^/api
            stateless: true
            json_login:
                check_path: /api/auth
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
       
        main:
            lazy: true
            provider: app_user_provider
           
    access_control:
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api$, roles: PUBLIC_ACCESS }
        - { path: ^/api/animals, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api/type_animals, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api/races, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api/categorie_buts, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }